### ISSUE TITLE
Make Fable Libraries explicitly distinct from Fable Bindings

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/Fable.Template.Library#6]
> Distinction between bindings and Fable libraries
>I know this is not always clear and can be confusing, so we may fix it later, but for now I'd like to keep the distinction between bindings and libraries for the reason [commented here](https://github.com/fable-compiler/fable-import/tree/7229f061e0ddeb172c785c11efce6c3f66b1313e#fable-import). Actually, there's no need to do anything about that in this repo but it's better to say this is not the template for a binding (for example in the README the name of the project sample is CustomJsBinding).

We should be explicit in the README about this distinction and if we make a separate template for Fable Bindings that we link to it.

**Comment by TheAngryByrd** [comment]
@alfonsogarciacaro do you have any specific verbiage you'd like to use for this or other links/references to clarify the two differences?

**Comment by alfonsogarciacaro** [comment]
It's not written anywhere yet 😅 Maybe something like this could work?

There are two kinds of Fable packages:

- **JS Bindings**: These don't contain any actual code, only signatures and attributes normally generated by [ts2fable](https://www.npmjs.com/package/ts2fable). They're just used to provide a type-safe to interact with a JS library from Fable.
- **Libraries**: These contain F# code that will be compiled to JS by Fable when being referenced by a consumer project.

The distinction is important because Fable can read metadata from .dll assemblies (like signatures and attributes) but not executable code, for that it needs the **F# sources**. For JS bindings _without actual code_ you don't need to worry as they can be distributed as any other Nuget package. However, Fable libraries need a couple of extra steps:

- First, the package must contain a folder named **fable** with the F# sources (and if necessary other files like JS scripts).
- The `fable` folder must contain an **.fsproj file with the same name as the Nuget package**.

This is not difficult to do and usually only requires adding a tag to your project file ([example](https://github.com/fable-compiler/fable-react-native/blob/6a7cc0e5074b985ef94e49a631cb8285eb9950c8/src/Fable.React.Native.fsproj#L32-L34)), but you need to make sure all the sources get into the package with the proper directory structure. Also, take into account Fable will just make a simple XML parsing to extract the source files from the .fsproj, so you should avoid MSBuild conditionals, etc.

Because Fable will compile your sources you must be careful with compiler directives too (like `#if MY_SYMBOL`, etc). Though you can use this to your advantage and do some logging in debug mode (`#if DEBUG`). And remember also that Fable will always define the `FABLE_COMPILER` symbol when compiling to JS.
